### ISSUE TITLE
Error with running main.py

### ISSUE THREAD

**Issue by MAli-Haider** [stevenzchen/pose-trainer#2]
Hi @stevenzchen  , I have built openpose from source and openpose demo worked perfectly for me.
But when I run the code with following arguments,

python main.py --mode evalute --video test\1.mp4 --exercise bicep_curls
It always returns with the same error

processing video file...
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    main()
  File "main.py", line 50, in main
    '--write_keypoint_json', output_path])
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Also could you guide me how did you convert your videos into numpy array files?

Thanks for your time

**Comment by stevenzchen** [comment]
Closing this out since the README has been updated with an example.
